language: php

env:
  global:
    - CC_TEST_REPORTER_ID=f424c3957298b215ddff899f624b534dac452ed703b42f70b74188a2edf0b5d0

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

install: composer install

notifications:
  email: false

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - cd tests
  - php run.php --coverage=clover
  - cd ..

matrix:
  allow_failures:
    - php: hhvm

after_success:
  - bash <(curl -s https://codecov.io/bash) -f tests/coverage/clover.xml

after_script:
  - cp tests/coverage/clover.xml ./clover.xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
